- name: configuring frontned
  hosts: frontned
  become: yes
  tasks:
  - name: disable nginx module
    ansible.builtin.command: module disable nginx

  - name: enable nginx:1.24
    ansible.builtin.command: enable nginx:1.24

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove default nginx conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy roboshop nginx conf
    ansible.builtin.copy:
      path: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted